### ISSUE TITLE
Custom subreddit bar gets wiped after every update

### ISSUE THREAD

**Issue by Pinatata** [bermudalocket/Tweaks-for-Reddit#17]
It has happened in the last 3 updates. I was hoping that once the app hit the App Store that the issue might've been rectified but that does not seem to be the case. The latest App Store update also wiped the custom subreddit bar. 

Is the file that stores the custom subreddit bar being reset with every update? Is there perhaps a better place to store user settings?

**Comment by bermudalocket** [comment]
In the latest update (1.8), I migrated the storage of the favorite subreddits from UserDefaults (stored on your computer) to CloudKit (stored in iCloud and accessible on all your devices). I will add some code to migrate saved favorite subreddits.

Sorry about that oversight. No more changes though, I promise!

**Comment by bermudalocket** [comment]
The transition to iCloud storage is complete as of 1.11
