### ISSUE TITLE
Scaling issue with popover menu with large custom subreddit list

### ISSUE THREAD

**Issue by Pinatata** [bermudalocket/Tweaks-for-Reddit#19]
I'm having issues using the popover menu once the custom subreddit list becomes large. I can't scroll up/down to see the other elements in the popover menu.

Not sure if there's a way to add scrolling within the popover menu. Otherwise, it may be better to explore different menu structures. For example, I notice Dark Reader's settings take me different page that is still displayed in the popover menu.

**Tweaks for Reddit Popover issue**
<img width="1280" alt="Screen Shot 2021-05-09 at 1 56 49 PM" src="https://user-images.githubusercontent.com/22414023/117582148-9ab16280-b0ce-11eb-9dfe-de1dc9c0e665.png">

**Dark Reader Settings Example**
<img width="218" alt="Screen Shot 2021-05-09 at 2 04 51 PM" src="https://user-images.githubusercontent.com/22414023/117582339-8de13e80-b0cf-11eb-8e98-da1500f7d820.png">

<img width="216" alt="Screen Shot 2021-05-09 at 2 04 58 PM" src="https://user-images.githubusercontent.com/22414023/117582350-99346a00-b0cf-11eb-824f-1cca3cee1260.png">

**Comment by bermudalocket** [comment]
Oh, that's no good. I know exactly why it's happening, though: https://github.com/bermudalocket/Tweaks-for-Reddit/blob/88bf11f5078828e14e46c911e5985f67499b3f67/redditweaks%20Extension/View/FavoriteSubredditsSectionView.swift#L72

I will explore options and push a fix to the Mac App Store.

**Comment by bermudalocket** [comment]
Version 1.10 fixes this and adds some customizability. It should push to the Mac App Store tomorrow, Friday, May 14.

**Comment by Pinatata** [comment]
Just got the 1.10 update on my end. The custom subreddit list scrolling looks perfect! However, the entire menu still has some scaling issues on my end. In fact, I noticed 2 different behaviors:

1. When in full-screen or desktop mode
<img width="1280" alt="Screen Shot 2021-05-16 at 9 06 56 AM" src="https://user-images.githubusercontent.com/22414023/118400295-a351ed80-b626-11eb-9075-6cad1e8546cf.png">

2. When in full-screen and menu bar comes down
<img width="1280" alt="Screen Shot 2021-05-16 at 9 07 03 AM" src="https://user-images.githubusercontent.com/22414023/118400300-a6e57480-b626-11eb-8322-ca7ce1531433.png">
(menu bar isn't in the screenshot but it is down)
