### ISSUE TITLE
Enabling and using "Endless scrolling" loses the ability to expand thumbnails

### ISSUE THREAD

**Issue by Fofer** [bermudalocket/Tweaks-for-Reddit#23]
Hi, I am really enjoying Tweaks for Reddit, thanks for making it! I am running Safari 14.0.3 on an M1 MacBook Pro with Big Sur 11.2.3 and having an issue:

When I enable "endless scrolling" and get to page 2 or later, I can no longer click these to expand the post or media:
http://i.imgur.com/I2aTKK1.png

When I disable "endless scrolling" and refresh the page, scroll down and click to get to page 2, and try again, it works.  It only stops working once I have re-enabled "endless scrolling."

**Comment by bermudalocket** [comment]
I discovered this yesterday and have already implemented a fix. Keep a look out for an update from the Mac App Store :)

**Comment by Fofer** [comment]
Thanks!  This is working great now with the latest version.
