### ISSUE TITLE
Live Comment Previews not working after updating to 1.12.

### ISSUE THREAD

**Issue by magn2o** [bermudalocket/Tweaks-for-Reddit#30]
It seems Live Comment Previews have stopped working after updating to 1.12. The "Live Comment Previews" tab within the the settings reports "Thank you for your support!", however, the debug tab states "Live Comment Previews: No".

I've tried toggling the function on/off, using the "restore purchases" option, and rebooting. None of which seem to have corrected the issue.

Versions:

macOS Big Sur (11.3.1)
Safari: 14.1 (16611.1.21.161.6)
Tweaks for Reddit: 1.12

![Screen Shot 2021-06-01 at 9 09 18 AM](https://user-images.githubusercontent.com/670196/120328713-190db880-c2b9-11eb-8f48-a46ab48131d7.png)
![Screen Shot 2021-06-01 at 8 58 46 AM](https://user-images.githubusercontent.com/670196/120327304-9c2e0f00-c2b7-11eb-9c93-016e26d2721e.png)
![Screen Shot 2021-06-01 at 8 55 47 AM](https://user-images.githubusercontent.com/670196/120327032-54a78300-c2b7-11eb-908e-2b24d23f9cf1.png)
![Screen Shot 2021-06-01 at 8 55 43 AM](https://user-images.githubusercontent.com/670196/120327034-54a78300-c2b7-11eb-830e-2d6d01993e6b.png)

**Comment by bermudalocket** [comment]
Damn, I thought this was fixed.

Will look into it and push a fix today

**Comment by bermudalocket** [comment]
@magn2o -- quick unrelated question. I've uploaded these screenshots at 2x resolution. Notice how the menu items in your screenshot (dark mode) are squished compared to mine (light mode)? 

1. Has this always been like this?
2. Do you have a custom resolution set? This *shouldn't* matter but IIRC there are resolution-related SwiftUI bugs.
3. What hardware are you using? And is it Intel or M1? (e.g. Intel MacBook Pro, M1 Mac Mini, etc)
4. Do you have any display accessibility options set? (e.g. custom zoom)


![CleanShot 2021-06-01 at 12 33 11@2x](https://user-images.githubusercontent.com/30004636/120359349-91827280-c2d5-11eb-8845-7d6dbe90c43c.jpg)
![CleanShot 2021-06-01 at 12 33 19@2x](https://user-images.githubusercontent.com/30004636/120359365-947d6300-c2d5-11eb-8963-efbdaf3a9296.jpg)

**Comment by magn2o** [comment]
1. Has this always been like this?

> Yes, it has always been like this.

2. Do you have a custom resolution set? This shouldn't matter but IIRC there are resolution-related SwiftUI bugs.

> No, I'm not using a custom resolution. My external displays are running @ 1440p (2560x1440).

3. What hardware are you using? And is it Intel or M1? (e.g. Intel MacBook Pro, M1 Mac Mini, etc)

> Those screenshots were taken on a MacBook Pro (15-inch, 2018) w/ Intel i7 running to external displays.

4. Do you have any display accessibility options set? (e.g. custom zoom)

> No,  I do not have any accessibility options set.

**Comment by bermudalocket** [comment]
I've got a fix for this issue (#30). Will be finishing it up and pushing the update tomorrow.

**Comment by bermudalocket** [comment]
1.12.1 finally pushed and awaiting App Store review

**Comment by magn2o** [comment]
@bermudalocket I can confirm that Live Comment Previews has been fixed, and the display/cropping issues of the text in the app window have been fixed.

Thank you!
