### ISSUE TITLE
App settings not working/displaying

### ISSUE THREAD

**Issue by cmdtacos** [bermudalocket/Tweaks-for-Reddit#31]
When I try to enable "Live preview comments in markdown" and it opens the app settings window (with 1 - Welcome, 2 - Connect to Safari, etc.) nothing appears in the right-hand window when I select options from the side bar. The only thing displayed is "Welcome to Tweaks for Reddit"

**Comment by baggachipz** [comment]
Same here. Screenshot:
<img width="937" alt="Screen Shot 2021-06-08 at 9 14 38 AM" src="https://user-images.githubusercontent.com/617372/121192085-92b62100-c83a-11eb-87a1-f1cf5f8144e8.png">

BTW, amazing extension. Lack of RES was the only thing keeping me from switching to Safari, and this does it for me! I want to purchase the in-app upgrade to support development but can't as it is now.

**Comment by bermudalocket** [comment]
Thanks for the report!

I'm a little confused about this one, so bear with me here. The screenshot @baggachipz shared looks fine to me, nothing seems to be missing on the Connect to Safari page. Is the wording confusing? I.e. the fact that it still says "Click the button below [...]" when there is no button?

@cmdtacos -- is the screenshot @baggachipz shared similar to what you see? Or do you quite literally see nothing at all in the right-hand view?

**Comment by baggachipz** [comment]
The issue seems to be that the tabs on the left overlap and therefore aren't always "clickable". In web-dev parlance, some negative `margin-top` causes `div`s to overlap and therefore the one beneath can't be read/selected even if it's visible beneath the other.

**Comment by bermudalocket** [comment]
> The issue seems to be that the tabs on the left overlap and therefore aren't always "clickable". In web-dev parlance, some negative `margin-top` causes `div`s to overlap and therefore the one beneath can't be read/selected even if it's visible beneath the other.

Ahhhh, I see. Another user had the same issue but it was resolved in 1.12.1. Can you confirm you're on the same version?

Also, could you both let me know which macOS version you're on, and whether you're on Intel or M1? Thanks!

**Comment by cmdtacos** [comment]
> Thanks for the report!
> 
> I'm a little confused about this one, so bear with me here. The screenshot @baggachipz shared looks fine to me, nothing seems to be missing on the Connect to Safari page. Is the wording confusing? I.e. the fact that it still says "Click the button below [...]" when there is no button?
> 
> @cmdtacos -- is the screenshot @baggachipz shared similar to what you see? Or do you quite literally see nothing at all in the right-hand view?

My issue was a bit different in that selecting anything from the sidebar didn't produce a change in the main panel but it seems to have fixed itself, everything is displaying fine now!
