### ISSUE TITLE
Extension not appearing in the App Store anymore?

### ISSUE THREAD

**Issue by gitatmax** [bermudalocket/Tweaks-for-Reddit#46]
Hey! It doesn't look like I'm able to get the extension anymore (due to my region)?
<img width="302" alt="CleanShot 2022-01-03 at 17 16 21@2x" src="https://user-images.githubusercontent.com/7244793/147986504-5bfba0da-83d3-4eec-a35c-8072e63ca1f4.png">

**Comment by bermudalocket** [comment]
Hi Max,

TFR is currently not available on the App Store due to my Apple Developer account lapsing. I simply can't afford the required payment at this time, but I do anticipate reviving it when I am able.

Sorry for any inconvenience.

**Comment by gitatmax** [comment]
@bermudalocket hey, fair enough! I look forward to it’s revival.

**Comment by bermudalocket** [comment]
The app should be back on the app store within the next day or so.

**Comment by gitatmax** [comment]
@bermudalocket Hey, I'm thrilled! I'm glad you got back to it. Please let me know how I can assist, if you'd like any help on something specific, still! Thanks for the heads up.
